config/routes.rb
Guildecontest::Application.routes.draw do
  match 'subscriptions/liked' => 'subscriptions#liked'
  match 'subscriptions/csv' => 'subscriptions#subscriptionsToCsv'
  match 'subscriptions/thanks/:id' => 'subscriptions#thanks', :as => :thanks
  match 'subscriptions/closed' => 'subscriptions#closed'
  
  resources :subscriptions, :except => :edit
  
  root :to => 'subscriptions#liked'
  #root :to => 'subscriptions#closed' #Change to this root path to close contest
end

app/models/canvas.rb
class Canvas

    class << self
      def parse_signed_request(secret_id,request)
        
		encoded_sig, payload = request.split('.', 2)
        
		sig = ""
        
		urldecode64(encoded_sig).each_byte { |b|
          sig << "%02x" % b
        }
        
		data = JSON.parse(urldecode64(payload))
          if data['algorithm'].to_s.upcase != 'HMAC-SHA256'
          raise "Bad signature algorithm: %s" % data['algorithm']
        end
        
		expected_sig = OpenSSL::HMAC.hexdigest('sha256', secret_id, payload)
        
		if expected_sig != sig
          raise "Bad signature"
        end
        
		return data
      end

      private

      def urldecode64(str)
        encoded_str = str.gsub('-','+').gsub('_','/')
        encoded_str += '=' while !(encoded_str.size % 4).zero?
        Base64.decode64(encoded_str)
      end
    end
	
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

	attr_accessible :title, :firstname, :lastname, :email, :city, :telephone, :newsletter
 
	validates :title,  :presence => true
	validates :firstname,  :presence => true
	validates :lastname,  :presence => true
	validates :email,  :presence => true,
				:uniqueness => true,
				:format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }
	validates :telephone,  :presence => true
    validates :terms, :acceptance => { :accept => 'yes' }
	
	#validate :oneSubscriptionByDay?
	
	#Add one subscription per day instead uniqueness email
	def oneSubscriptionPerDay?
		@subscription = Subscription.where(:email => email, created_at => Date.today.to_s)
		
		if @subscription
			errors.add(:email, "One subscription by day"+@subscription.to_s+Date.today.to_s)
		end
	end
	
	def self.total_by_day(date)
      where("date(created_at) = ?",date).count()
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "password", only: [:index, :subscriptionsToCsv]
  
  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
	
    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  #Export DATA in CSV format
  def subscriptionsToCsv
    @subscriptions = Subscription.all
    
    require 'csv'
    
    csv_data = CSV.generate :col_sep => "," do |csv|
      #header
      csv << ["title","firstname", "lastname", "email","city","telephone","newsletter"]
      @subscriptions.each do |subscription| 
        csv << [subscription.title, subscription.firstname, subscription.lastname, subscription.email, subscription.city, subscription.telephone, subscription.newsletter]
      end
    end
    
    send_data csv_data, :type => "text/csv", :disposition => 'attachment'
  end
  
  # GET /subscriptions/thanks
  def thanks
    @subscription = Subscription.find(params[:id])
	
    respond_to do |format|
      format.html # thanks.html.erb
    end
  end
  
  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscription }
    end
  end

  # GET /subscriptions/liked
  def liked
    #Get FB http parameters
    #Parse it with Canvas rb class
    begin
      @decoded_request = Canvas.parse_signed_request("YOUR APP SECRET",params[:signed_request])
      @liked = @decoded_request['page']['liked'] #Store if page is liked by the user
    rescue
      @liked = false
      @alert = "ERROR : You don't connect to facebook. Set up AppID & App Secret"
    end
    
    respond_to do |format|
      #If user like the page
      if @liked
        format.html { redirect_to '/subscriptions/new' } #Access to register form
      else
        format.html #Else go to liked page
      end
    end
  end
  
  # GET /subscriptions/closed
  def closed
    respond_to do |format|
      format.html # closed.html.erb
    end
  end
  
  # GET /subscriptions/new
  # GET /subscriptions/new.json
  def new
    @subscription = Subscription.new
	
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscription }
    end
  end

  # GET /subscriptions/1/edit
  def edit
    @subscription = Subscription.find(params[:id])
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(params[:subscription])

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to thanks_url(:id => @subscription) }
        format.json { render json: @subscription, status: :created, location: @subscription }
      else
        format.html { render action: "new" }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PUT /subscriptions/1
  # PUT /subscriptions/1.json
  def update
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      if @subscription.update_attributes(params[:subscription])
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to subscriptions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ActionView::Base.field_error_proc = Proc.new do |html_tag, instance|
    errors = Array(instance.error_message).join(',')
    %(<div class="error">#{html_tag}<img src="/assets/alert.png" title="#{errors}" /></div><div class="error">#{errors}</div>).html_safe
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facebook Contest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="fb-root"></div>
<script>

  window.fbAsyncInit = function() {
    FB.init({
      appId      : 'YOUR FACEBOOK APP ID', // App ID
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });

    // Additional initialization code here
  };

  // Load the SDK Asynchronously
  (function(d){
    var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement('script'); js.id = id; js.async = true;
    js.src = "//connect.facebook.net/fr_CA/all.js";
    ref.parentNode.insertBefore(js, ref);
  }(document));
   
</script>

<% if @alert %>
  <div id="alert" class="error">
    <%= @alert %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/subscriptions/_form.html.erb
<script type="text/javascript">

	function validterms() {
		if(document.getElementById("accept").checked) {
			return true;
		} else {
			alert("Vous devez accepter les conditions du concours pour enregistrer votre participation");
			return false;
		}
	}

</script>

<%= form_for(@subscription) do |f| %>
  <table>
	<tr>
		<td class="label">Titre &nbsp;</td>
		<td><%= f.select :title, { "Madame" => "Madame", "Monsieur" => "Monsieur" }  %></td>
	</tr>
	<tr>
		<td class="label">Pr&eacute;nom*&nbsp;</td>
		<td><%= f.text_field :firstname %></td>
	</tr>
	<tr>
		<td class="label">Nom*&nbsp;</td>
		<td><%= f.text_field :lastname %></td>
	</tr>
	<tr>
		<td class="label">Courriel*&nbsp;</td>
		<td><%= f.email_field :email %></td>
	</tr>
	<tr>
		<td class="label">T&eacute;l&eacute;phone*&nbsp;</td>
		<td><%= f.text_field :telephone %></td>
	</tr>
	<tr>
		<td class="label"><%= f.check_box :newsletter %></td><td class="checkbox-title">Je souhaite recevoir l'infolettre de La Compagnie</td>
	</tr>
	<tr>
		<td class="label"><%= check_box_tag 'accept', '', false, :class => "regular-checkbox" %></td>
		<td class="checkbox-title">
			J'accepte 
			<a href="#" onClick="window.open('/rules?v=201311081635','_blank','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, copyhistory=no, width=900, height=700');">les conditions et modalit&eacute;s</a>
			du concours
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="actions">
				<%= submit_tag("Participer", :disabled => false, :class => 'submit', :onclick => "return validterms();") %>
			</div>
		</td>
	</tr>
	<tr id="required">
		<td></td>
		<td style="text-align: right;">* Champ obligatoire</td>
	</tr>
  </table>
  
<% end %>

app/views/subscriptions/closed.html.erb
<%= image_tag 'closed.jpg', :id => 'thanks', :alt => "Le concours est terminé", :usemap => "#map" %>
<map name="map">
  <area shape="rect" coords="140,335,670,383" href="#" target="_blank" alt="Site de La Compagnie" />
</map>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<% start_date = !Subscription.first.nil? ? Subscription.first.created_at : DateTime.current %>
<% end_date = !Subscription.last.nil? ? Subscription.last.created_at : DateTime.current %>

<h1>Listing subscriptions</h1>

<script type="text/javascript" charset="utf-8">
  $(function () {
    Highcharts.setOptions({
      global : {
        useUTC : false
      }
    });
    
    new Highcharts.Chart({
      chart: { renderTo: 'subscriptions_chart' },
	    title: { text: 'Subscriptions by Day' },
      xAxis: { type: 'datetime' },
      yAxis: {
        title: { text: 'Number of subscription'},
		    min: 0
      },
	    tooltip: {
        formatter: function () {
          return Highcharts.dateFormat("%B %e %Y", this.x) + ': ' +
            this.y + " subscription(s)";
        }
      },
      series: [{
	    pointInterval: <%= 1.day * 1000 %>,
        pointStart: <%= start_date.to_i * 1000 %>,
        data: <%= (start_date.to_date..end_date.to_date).map { |date| Subscription.total_by_day(date).to_f }.inspect %>
      }]
    });
  });
</script>

<div id="subscriptions_chart" style="width: 560px; height: 300px;"></div>

<h3 style="color:#E00007;"><%= @subscriptions.count %> inscrits</h3>

<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Email</th>
    <th>City</th>
    <th>Telephone</th>
    <th>Newsletter</th>
	<th>Date</th>
  </tr>

<% @subscriptions.each do |subscription| %>
  <tr>
    <td><%= link_to subscription.id, subscription_path(subscription) %></td>
    <td><%= subscription.title %></td>
    <td><%= subscription.firstname %></td>
    <td><%= subscription.lastname %></td>
    <td><%= subscription.email %></td>
    <td><%= subscription.city %></td>
    <td><%= subscription.telephone %></td>
    <td><%= subscription.newsletter %></td>
    <td><%= subscription.created_at %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Get Subscriptions in CSV', '/subscriptions/csv.csv' %>

app/views/subscriptions/liked.html.erb
<%= image_tag 'like.jpg', :id => 'like', :width => "810px", :class => 'like', :alt => "Aime notre page" %>

app/views/subscriptions/new.html.erb
<div id="form">
	<%= image_tag 'header.jpg', :id => 'header', :width => "810px", :class => 'form-header', :alt => "La Guilde Culinaire" %>
	<div id="fields">
		<%= render 'form' %>
	</div>
</div>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @subscription.title %>
</p>

<p>
  <b>Firstname:</b>
  <%= @subscription.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @subscription.lastname %>
</p>

<p>
  <b>Email:</b>
  <%= @subscription.email %>
</p>

<p>
  <b>City:</b>
  <%= @subscription.city %>
</p>

<p>
  <b>Telephone:</b>
  <%= @subscription.telephone %>
</p>

<p>
  <b>Newsletter:</b>
  <%= @subscription.newsletter %>
</p>

<%= link_to 'Back', subscriptions_path %> |
<%= link_to 'Destroy', @subscription, confirm: 'Are you sure?', method: :delete %>

app/views/subscriptions/thanks.html.erb
<%= image_tag 'thanks.jpg', :id => 'thanks', :alt => "Consulter notre site web", :usemap => "#map" %>
<map name="map">
  <area shape="rect" coords="140,335,670,383" href="#" target="_blank" alt="Site de La Compagnie" />
</map>